### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by mgit7** [abhishekdhaduvai/boilerplate#1]
I get an error trying to get the React seed repo project to run but I got the seed-application-master to run using the instructions stated in the ReadMe file. It seems to not recognize the start script that is declared in the package.json file. I tried install nodemon manually and still had no luck. 

> [0] 'nodemo' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'server' is not recognized as an internal or external command,
[1] operable program or batch file.
[2] 'webpac' is not recognized as an internal or external command,
[2] operable program or batch file.
[1] server/app.js' exited with code 1
[0] nodemo exited with code 1
[2] webpac exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-seed@1.0.0 start: `concurrently 'nodemon server/app.js' 'webpack --config webpack.common.js -w'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-seed@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manny\AppData\Roaming\npm-cache\_logs\2018-04-03T04_05_41_797Z-debug.log

Any suggestions?

**Comment by mgit7** [comment]
Okay I did as you said and got the React app up and running but Im confused on how to edit the source code of the React app. In another predix repo "px-sample-app-react-master", there is a directory called src that uses react and jsx syntax but im not really seeing that here. Am I missing something?

I tried creating my own React project by following this link but I can't seem to follow along:

[How to Deploy a React.js App to GE Predix (a Tic Tac Toe Example)](https://blog.altoros.com/how-to-deploy-a-react-js-app-to-ge-predix-a-tic-tac-toe-example.html)

**Comment by abhishekdhaduvai** [comment]
Hi @mgit7 

Sorry for the confusion. There are 2 React branches in this repo. The 'react-sample' branch is an example application with sample data, while the 'react' branch doesn't have all the example data, so that you can quickly start building on top of it.

Just like the px-sample-app-react repo, this too has a directory called src that uses React and jsx syntax. Make sure you're on the right branch. You can get to this branch by running ```git checkout react```

**Comment by abhishekdhaduvai** [comment]
Closing the issue. You can reopen it if you're still having issues running it.
